version: "3.3"
services:
  mc4-producing: # block-producing node
    image: coincodile/cardano-pool:latest
    network_mode: host
    volumes:
      - $PWD/config/local/:/config
    environment:
      - HOST_ADDR=0.0.0.0
      - NODE_PORT=3000
      - NODE_NAME=test-producing
      - NODE_TOPOLOGY=127.0.0.1:3001/1
      - NODE_RELAY=False
      - CARDANO_NETWORK=test
      - EKG_PORT=12888
      - PROMETHEUS_PORT=12898
      - PROMETHEUS_HOST=127.0.0.1
      - POOL_PLEDGE=100000000000
      - POOL_COST=340000000
      - POOL_MARGIN=0.05
      - METADATA_URL=https://coincodile.com/assets/metadata.json
      - PUBLIC_RELAY_IP=PUBLIC
    command: --start --staking --create
    restart: unless-stopped
  mc4-relay1: # relay node
    image: coincodile/cardano-pool:latest
    network_mode: host
    volumes:
      - $PWD/config/local/:/config
    environment:
      - HOST_ADDR=0.0.0.0
      - NODE_PORT=3001
      - NODE_NAME=test-relay1
      - NODE_TOPOLOGY=127.0.0.1:3000/1
      - NODE_RELAY=True
      - CARDANO_NETWORK=test
      - EKG_PORT=12889
      - PROMETHEUS_PORT=12899
      - PROMETHEUS_HOST=127.0.0.1
    command: --start
    restart: unless-stopped